class DocusignService:
    # TODO Implement this service and its functions
    def __init__(self, integrator_key, base_url, access_token):
        ...

    def create_envelope(self, document, sender, recipients, message):
        ...

    def get_envelope(self, envelope_id):
        ...

    def void_envelope(self, envelope_id):
        ...

    def send_reminder(self, envelope_id, recipient_id):
        ...

    def get_envelope_status(self, envelope_id):
        ...

    def decline_envelope(self, envelope_id):
        ...
